# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: False
dist: focal

python:
  - 2.7
  - 3.7
virtualenv:
    system_site_package: true

addons:
  apt:
    sources:
    - sourceline: 'ppa:edd/misc'
    packages:
    - python-numpy
    - libquantlib0-dev

before_install:
 - pip install -r requirements.txt
install:
    make build
script:
 - python -m unittest discover
#notifications:
  #email: 
    #- dpinte@enthought.com
