# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 2.7
  - 3.6
virtualenv:
    system_site_package: true
before_install:
 - sudo add-apt-repository -y ppa:edd/misc
 - sudo apt-get update
 - sudo apt-get install -qq python-numpy python-six
 - sudo apt-get install libquantlib0-dev
 - pip install -r requirements.txt
install:
    make build
script:
 - python -m unittest discover
notifications:
  email: 
    - dpinte@enthought.com
