[build-system]
requires=["setuptools", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "quantlib-cython"
authors = [
    {name = "Didrik Pinte"},
    {name = "Patrick Henaff"},
]
dependencies = [
    "pandas",
    "tabulate",
]
license = {file = "LICENSE.txt"}
readme  = "README.md"
version = "1.40"

[tool.setuptools.packages.find]
include = ["quantlib*"]

[tool.setuptools.exclude-package-data]
"*" = ["**.cpp", "**.pyx"]

[tool.uv]
config-settings = { "--build-option" = "build_ext -j6" }

[[tool.uv.index]]
name = "serenitas"
publish-url = "http://dev.serenitas/api/packages/Serenitas/pypi"
url = "http://dev.serenitas/api/packages/Serenitas/pypi/simple"
